-- Disposable database: campaign-owned form, respondent snapshot and privacy boundaries.
SET request.jwt.claim.sub='10000000-0000-0000-0000-000000000001';
SET ROLE authenticated;
DO $$ DECLARE org uuid; annual uuid; scheduled_annual uuid; scheduled_feedback uuid; empty_feedback uuid; template_feedback uuid; copied uuid; revision bigint; source_prompt text; form_payload jsonb; feedback uuid; legacy uuid; q uuid; reviewer_payload jsonb; source_template uuid; copy_campaign uuid;
BEGIN
 SELECT organization_id INTO org FROM public.people WHERE id='30000000-0000-0000-0000-000000000001';
 INSERT INTO public.campaigns(organization_id,name,campaign_type,timezone) VALUES(org,'Local form annual','annual_appraisal','Europe/London') RETURNING id INTO annual;
 revision := public.start_campaign_form(annual,'50000000-0000-0000-0000-000000000001');
 ASSERT revision=1;
 ASSERT (SELECT count(*)=2 FROM public.campaign_questions WHERE campaign_id=annual);
 SELECT id,prompt INTO copied,source_prompt FROM public.campaign_questions WHERE campaign_id=annual AND type='text';
 UPDATE public.template_questions SET prompt='Source changed later' WHERE id='60000000-0000-0000-0000-000000000001';
 ASSERT (SELECT prompt=source_prompt FROM public.campaign_questions WHERE id=copied);
 form_payload := jsonb_build_array(
   jsonb_build_object('id',copied,'type','text','prompt','Campaign-specific reflection','required',true),
   jsonb_build_object('id',gen_random_uuid(),'type','rating','prompt','How did this year go?','required',false,'scale',jsonb_build_object('min',1,'max',5)));
 revision := public.save_campaign_form(annual,revision,form_payload);
 ASSERT revision=2;
 ASSERT (SELECT count(*)=2 FROM public.campaign_questions WHERE campaign_id=annual);
 ASSERT (SELECT sort_order=0 AND prompt='Campaign-specific reflection' FROM public.campaign_questions WHERE id=copied);
 ASSERT (SELECT prompt='Source changed later' FROM public.template_questions WHERE id='60000000-0000-0000-0000-000000000001');
 INSERT INTO public.templates(organization_id,name) VALUES(org,'Disposable source') RETURNING id INTO source_template;
 INSERT INTO public.template_questions(template_id,organization_id,type,prompt) VALUES(source_template,org,'text','Original source');
 INSERT INTO public.campaigns(organization_id,name,campaign_type) VALUES(org,'Deleted source copy','annual_appraisal') RETURNING id INTO copy_campaign;
 PERFORM public.start_campaign_form(copy_campaign,source_template);
 UPDATE public.templates SET archived_at=now() WHERE id=source_template;
 ASSERT (SELECT count(*)=1 AND min(prompt)='Original source' FROM public.campaign_questions WHERE campaign_id=copy_campaign);
 INSERT INTO public.campaigns(organization_id,name,campaign_type,timezone) VALUES(org,'Local scheduled annual','annual_appraisal','Europe/London') RETURNING id INTO scheduled_annual;
 revision := public.start_campaign_form(scheduled_annual,NULL);
 PERFORM public.save_campaign_form(scheduled_annual,revision,jsonb_build_array(jsonb_build_object('id',gen_random_uuid(),'type','text','prompt','Scheduled reflection','required',true)));
 PERFORM public.save_appraisal_participants(scheduled_annual,jsonb_build_array(jsonb_build_object('person_id','30000000-0000-0000-0000-000000000001','manager_person_id',null)));
 PERFORM public.save_annual_draft_timing(scheduled_annual,'later','2999-07-01',NULL);
 PERFORM public.schedule_appraisal_campaign(scheduled_annual,'2999-07-01');
 ASSERT (SELECT status='scheduled' AND questions_frozen_at IS NOT NULL FROM public.campaigns WHERE id=scheduled_annual);
 ASSERT (SELECT count(*)=1 AND min(prompt)='Scheduled reflection' FROM public.campaign_questions WHERE campaign_id=scheduled_annual);
 SELECT form_revision INTO revision FROM public.campaigns WHERE id=annual;
 DELETE FROM public.templates WHERE id=source_template;
 ASSERT (SELECT template_id IS NULL AND organization_id=org FROM public.campaigns WHERE id=copy_campaign);
 ASSERT (SELECT count(*)=1 AND min(prompt)='Original source' FROM public.campaign_questions WHERE campaign_id=copy_campaign);
 PERFORM public.save_campaign_form(copy_campaign,1,'[]');
 PERFORM public.save_appraisal_participants(copy_campaign,jsonb_build_array(jsonb_build_object('person_id','30000000-0000-0000-0000-000000000001','manager_person_id',null)));
 PERFORM public.save_annual_draft_timing(copy_campaign,'now',NULL,NULL);
 BEGIN PERFORM public.activate_campaign(copy_campaign); RAISE EXCEPTION 'expected empty local form denial';
 EXCEPTION WHEN raise_exception THEN IF SQLERRM<>'Add at least one question' THEN RAISE; END IF; END;
 ASSERT (SELECT status='draft' AND questions_frozen_at IS NULL FROM public.campaigns WHERE id=copy_campaign);
 BEGIN PERFORM public.save_campaign_form(annual,1,form_payload); RAISE EXCEPTION 'expected revision conflict';
 EXCEPTION WHEN raise_exception THEN IF SQLERRM<>'This form changed elsewhere. Reload before saving' THEN RAISE; END IF; END;
 BEGIN PERFORM public.save_campaign_form(annual,revision,'[{"id":"00000000-0000-0000-0000-000000000001","type":"text","prompt":""}]'::jsonb); RAISE EXCEPTION 'expected invalid question';
 EXCEPTION WHEN raise_exception THEN IF SQLERRM<>'Choose supported questions with valid text' THEN RAISE; END IF; END;
 ASSERT (SELECT count(*)=2 FROM public.campaign_questions WHERE campaign_id=annual);
 PERFORM public.save_appraisal_participants(annual,jsonb_build_array(jsonb_build_object('person_id','30000000-0000-0000-0000-000000000001','manager_person_id','30000000-0000-0000-0000-000000000002')));
 PERFORM public.save_annual_draft_timing(annual,'now',NULL,NULL);
 PERFORM public.activate_campaign(annual);
 ASSERT (SELECT status='active' AND questions_frozen_at IS NOT NULL FROM public.campaigns WHERE id=annual);
 ASSERT (SELECT string_agg(prompt,'|' ORDER BY sort_order)='Campaign-specific reflection|How did this year go?' FROM public.campaign_questions WHERE campaign_id=annual);
 BEGIN PERFORM public.save_campaign_form(annual,revision,form_payload); RAISE EXCEPTION 'expected frozen form';
 EXCEPTION WHEN raise_exception THEN IF SQLERRM<>'Only a draft campaign form can be edited' THEN RAISE; END IF; END;

 feedback := public.create_feedback_360_draft('Local form 360',org);
 template_feedback := public.create_feedback_360_draft('Local template 360',org);
 revision := public.start_campaign_form(template_feedback,'80000000-0000-0000-0000-000000000001');
 ASSERT (SELECT count(*)>0 FROM public.campaign_questions WHERE campaign_id=template_feedback);
 SELECT id INTO q FROM public.campaign_questions WHERE campaign_id=template_feedback ORDER BY sort_order LIMIT 1;
 PERFORM public.save_campaign_form(template_feedback,revision,jsonb_build_array(jsonb_build_object('id',q,'type','text','prompt','Campaign-specific anonymous feedback','required',true)));
 ASSERT NOT EXISTS(SELECT 1 FROM public.template_questions WHERE template_id='80000000-0000-0000-0000-000000000001' AND prompt='Campaign-specific anonymous feedback');
 revision := public.start_campaign_form(feedback,NULL);
 q := gen_random_uuid();
 revision := public.save_campaign_form(feedback,revision,jsonb_build_array(jsonb_build_object('id',q,'type','rating','prompt','Feedback rating','required',true,'scale',jsonb_build_object('min',1,'max',5))));
 ASSERT revision=2;
 BEGIN PERFORM public.save_campaign_form(feedback,revision,jsonb_build_array(jsonb_build_object('id',q,'type','single_choice','prompt','Unsafe','options',jsonb_build_array('A','B')))); RAISE EXCEPTION 'expected 360 type rejection';
 EXCEPTION WHEN raise_exception THEN IF SQLERRM<>'Choose supported questions with valid text' THEN RAISE; END IF; END;
 SELECT jsonb_agg(jsonb_build_object('person_id',id,'relationship','peer')) INTO reviewer_payload FROM public.people WHERE email LIKE 'workflow%@example.test';
 empty_feedback := public.create_feedback_360_draft('Empty local 360',org);
 PERFORM public.start_campaign_form(empty_feedback,NULL);
 PERFORM public.save_feedback_360_cohort(empty_feedback,'30000000-0000-0000-0000-000000000001',reviewer_payload);
 PERFORM public.save_feedback_360_timing(empty_feedback,'now',NULL,NULL);
 BEGIN PERFORM public.finalize_feedback_360_draft(empty_feedback,true); RAISE EXCEPTION 'expected empty 360 denial';
 EXCEPTION WHEN raise_exception THEN IF SQLERRM<>'Add a non-empty rating/text form' THEN RAISE; END IF; END;
 ASSERT (SELECT status='draft' AND questions_frozen_at IS NULL FROM public.campaigns WHERE id=empty_feedback);
 legacy := public.create_feedback_360('Local legacy form','30000000-0000-0000-0000-000000000001',reviewer_payload,'80000000-0000-0000-0000-000000000001');
 SELECT id INTO q FROM public.campaign_questions WHERE campaign_id=legacy ORDER BY sort_order LIMIT 1;
 BEGIN PERFORM public.save_campaign_form(legacy,0,jsonb_build_array(jsonb_build_object('id',q,'type','rating','prompt','','required',true))); RAISE EXCEPTION 'expected conversion rollback';
 EXCEPTION WHEN raise_exception THEN IF SQLERRM<>'Choose supported questions with valid text' THEN RAISE; END IF; END;
 ASSERT (SELECT questions_frozen_at IS NOT NULL FROM public.campaigns WHERE id=legacy);
 revision := public.save_campaign_form(legacy,0,jsonb_build_array(jsonb_build_object('id',q,'type','rating','prompt','Edited legacy 360','required',true)));
 ASSERT revision=1;
 ASSERT (SELECT questions_frozen_at IS NULL FROM public.campaigns WHERE id=legacy);
 ASSERT (SELECT count(*)=1 AND min(prompt)='Edited legacy 360' FROM public.campaign_questions WHERE campaign_id=legacy);
 BEGIN PERFORM public.save_campaign_form((SELECT id FROM public.campaigns WHERE name='Legacy protected'),0,'[]'); RAISE EXCEPTION 'expected protected conversion denial';
 EXCEPTION WHEN raise_exception THEN IF SQLERRM<>'This 360 draft has delivery or private feedback data and cannot be converted' THEN RAISE; END IF; END;
 PERFORM public.save_feedback_360_cohort(feedback,'30000000-0000-0000-0000-000000000001',reviewer_payload);
 PERFORM public.save_feedback_360_timing(feedback,'now',NULL,NULL);
 PERFORM public.finalize_feedback_360_draft(feedback,true);
 ASSERT (SELECT status='active' AND questions_frozen_at IS NOT NULL FROM public.campaigns WHERE id=feedback);
 ASSERT (SELECT count(*)=1 FROM public.campaign_questions WHERE campaign_id=feedback);
 BEGIN PERFORM public.save_campaign_form(feedback,revision,'[]'); RAISE EXCEPTION 'expected frozen 360';
 EXCEPTION WHEN raise_exception THEN IF SQLERRM<>'Only a draft campaign form can be edited' THEN RAISE; END IF; END;
 scheduled_feedback := public.create_feedback_360_draft('Local scheduled 360',org);
 revision := public.start_campaign_form(scheduled_feedback,NULL);
 PERFORM public.save_campaign_form(scheduled_feedback,revision,jsonb_build_array(jsonb_build_object('id',gen_random_uuid(),'type','text','prompt','Scheduled anonymous feedback','required',true)));
 PERFORM public.save_feedback_360_cohort(scheduled_feedback,'30000000-0000-0000-0000-000000000001',reviewer_payload);
 PERFORM public.save_feedback_360_timing(scheduled_feedback,'later','2999-07-01',NULL);
 PERFORM public.finalize_feedback_360_draft(scheduled_feedback,true);
 ASSERT (SELECT status='scheduled' AND questions_frozen_at IS NOT NULL FROM public.campaigns WHERE id=scheduled_feedback);
 ASSERT (SELECT count(*)=1 AND min(prompt)='Scheduled anonymous feedback' FROM public.campaign_questions WHERE campaign_id=scheduled_feedback);
END $$;
RESET ROLE;
DO $$ DECLARE annual uuid; feedback uuid; legacy uuid; token text; BEGIN
 SELECT id INTO annual FROM public.campaigns WHERE name='Local form annual';
 SELECT id INTO feedback FROM public.campaigns WHERE name='Local form 360';
 SELECT o.payload->>'raw_token' INTO token FROM public.email_outbox o WHERE o.payload->>'campaign_id'=annual::text LIMIT 1;
 ASSERT token IS NOT NULL;
 ASSERT (SELECT string_agg(prompt,'|' ORDER BY sort_order)='Campaign-specific reflection|How did this year go?' FROM public.respond_get_questions(token));
 ASSERT EXISTS(SELECT 1 FROM private.feedback_360_contracts WHERE campaign_id=feedback);
 ASSERT NOT EXISTS(SELECT 1 FROM private.feedback_360_contracts WHERE campaign_id=(SELECT id FROM public.campaigns WHERE name='Empty local 360'));
 ASSERT NOT EXISTS(SELECT 1 FROM public.access_tokens t JOIN public.campaign_assignments a ON a.id=t.assignment_id WHERE a.campaign_id=(SELECT id FROM public.campaigns WHERE name='Empty local 360'));
 SELECT id INTO legacy FROM public.campaigns WHERE name='Local legacy form';
 ASSERT NOT EXISTS(SELECT 1 FROM private.feedback_360_contracts WHERE campaign_id=legacy);
 ASSERT EXISTS(SELECT 1 FROM private.feedback_360_contracts WHERE campaign_id=(SELECT id FROM public.campaigns WHERE name='Legacy protected'));
 ASSERT (SELECT count(*)>=5 FROM public.access_tokens t JOIN public.campaign_assignments a ON a.id=t.assignment_id WHERE a.campaign_id=feedback);
 BEGIN UPDATE public.campaign_questions SET prompt='Unsafe late edit' WHERE campaign_id=annual; RAISE EXCEPTION 'expected annual snapshot lock';
 EXCEPTION WHEN raise_exception THEN IF SQLERRM<>'Campaign questions are frozen' THEN RAISE; END IF; END;
 BEGIN DELETE FROM public.campaign_questions WHERE campaign_id=feedback; RAISE EXCEPTION 'expected 360 snapshot lock';
 EXCEPTION WHEN raise_exception THEN IF SQLERRM<>'Campaign questions are frozen' THEN RAISE; END IF; END;
END $$;
