import { SiteChrome } from "@/components/layout/SiteChrome";
import { ContentSection, PageHero, RelatedLinks, TextLink, homeCrumb } from "@/components/marketing/PageSections";
import { JsonLd } from "@/components/seo/JsonLd";
import { pageMetadata } from "@/lib/metadata";
import { breadcrumbSchema } from "@/lib/schema";

const title = "360 Feedback Software for UK Teams | Planned Features";
const description = "Explore the planned 360 feedback workflow for Appraisal Software and prepare with free templates and questions. Multi-rater collection and anonymity are not yet available.";
export const metadata = pageMetadata({ title, description, path: "/360-feedback-software" });
export default function Page() { return <SiteChrome>
  <JsonLd data={breadcrumbSchema([{ name: "Home", path: "/" }, { name: "360 Feedback Software", path: "/360-feedback-software" }])} />
  <PageHero eyebrow="Planned product capability" title="360 Feedback Software" description={description} breadcrumbs={[homeCrumb(), { label: "360 Feedback Software", href: "/360-feedback-software" }]} />
  <ContentSection title="What is available now?"><p>Appraisal Software currently supports employee self-assessments and manager responses within appraisal campaigns. Peer and direct-report collection, anonymity controls, Self vs Others analytics and PDF/CSV exports are planned; they are not available in the current product.</p><p>For the implemented review workflow, see <TextLink href="/how-it-works">how Appraisal Software works</TextLink>. You can use the free resources below to prepare a 360 exercise independently while the product capability is being developed.</p></ContentSection>
  <ContentSection title="What 360 feedback software should help you do"><p>A multi-rater process collects observations about a subject from people who see their work from different perspectives. The useful parts are choosing relevant reviewers, asking observable questions, tracking responses and discussing themes with the subject.</p><p>For UK small teams, the challenge is often coordinating the exercise without creating a large administrative process. A focused question set and a clear explanation of privacy matter more than a long report.</p></ContentSection>
  <ContentSection title="The planned workflow"><ol className="list-decimal space-y-3 pl-5"><li>Choose the subject and a short form that matches the development purpose.</li><li>Assign reviewers by relationship: self, manager, peers and direct reports.</li><li>Explain who will see the responses and how names will be handled before collecting feedback.</li><li>Track completion and remind outstanding reviewers.</li><li>Compare perspectives and agree practical development actions.</li></ol><p>This describes the intended product direction, not a promise of a release date or final feature set.</p></ContentSection>
  <ContentSection title="Anonymity and reporting need clear rules"><p>Removing names alone does not guarantee anonymity. Small groups and distinctive comments can identify a reviewer. The planned controls need to support the expectations explained to respondents.</p><p>Self vs Others comparisons can highlight differences in perspective. They should start a conversation, rather than label one group’s rating as the truth. Our <TextLink href="/360-feedback-examples">fictional feedback examples</TextLink> show how to interpret themes carefully.</p></ContentSection>
  <RelatedLinks title="Prepare your 360 process now" links={[{ href: "/360-feedback-template", label: "360 feedback template", copy: "Copy or print a form with an example rating scale." }, { href: "/360-feedback-questions", label: "360 feedback questions", copy: "Select prompts by behaviour and reviewer relationship." }, { href: "/360-degree-feedback", label: "What is 360 degree feedback?", copy: "Understand the purpose, process and limitations." }]} />
</SiteChrome>; }
